### PR TITLE
Setup Prettier on Server

### PR DESCRIPTION
**Pull request by parsa111**
This PR features #54 

### Description 

This PR adds the prettier on server side.

### CODE REVIEW

**Comment by oliviergoulet5** [comment]
I get the following error when I run `npm I`:

```node
> server@1.0.0 prepare
> husky install

.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/oliviergoulet/Projects/PrivaNote/server
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oliviergoulet/.npm/_logs/2021-09-24T04_07_32_129Z-debug.log
```

If you (@parsa111) delete your node_modules and run `npm I` do you get the same error?

**Comment by thejasonxie** [comment]
> I get the following error when I run `npm i`:
> 
> ```js
> > server@1.0.0 prepare
> > husky install
> 
> .git can't be found (see https://git.io/Jc3F9)
> npm ERR! code 1
> npm ERR! path /Users/oliviergoulet/Projects/PrivaNote/server
> npm ERR! command failed
> npm ERR! command sh -c husky install
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/oliviergoulet/.npm/_logs/2021-09-24T04_07_32_129Z-debug.log
> ```
> 
> If you (@parsa111) delete your node_modules and run `npm i` do you get the same error? And if the answer is yes then I believe it's because husky expects the .git to be in the same directory as package.json. We would need to figure out how we could reference the .git from the parent folder (change path? or would that break during something like deployment?). We can discuss.

Same issue with the setup-prettier-client branch. With this branch, it seems that its looking for the .git folder in the server directory when the .git folder is in the root project directory. We can fix this with `"prepare": "cd .. && husky install"` but I am not sure if this is what we want.

reference: https://typicode.github.io/husky/#/?id=custom-directory

**Review by EHSANHAZARI — APPROVED** [review]

**Review by thejasonxie — APPROVED** [review]
Setup husky and pretter, as well as fixed future merge conflicts with main

**Review by EHSANHAZARI — APPROVED** [review]

**Review by thejasonxie — APPROVED** [review]

**Review by oliviergoulet5 — APPROVED** [review]
I tested this on my own machine and both client and server use their own prettier configs on pre-commits. This is the intended behaviour and it works flawlessly. Good work!

**Pull request merged**
