### PR TITLE
Setup Prettier on Client

### PR DESCRIPTION
**Pull request by parsa111**
This PR feature #24 

### Description 

This PR adds the prettier on client side.

### CODE REVIEW

**Review by thejasonxie — CHANGES_REQUESTED** [review]
I get an error during npm install. When it gets to the prepare script, husky cannot find the .git directory. Husky is looking for the .git folder in the client directory when it is in the root project directory. reference: https://typicode.github.io/husky/#/?id=custom-directory

If we change the prepare script statement to `"prepare": "cd .. && husky install"`, it solves the issue but I am not sure that this is what we want. Can anyone confirm?

**Comment by oliviergoulet5** [comment]
> I get an error during npm install. When it gets to the prepare script, husky cannot find the .git directory. Husky is looking for the .git folder in the client directory when it is in the root project directory. reference: https://typicode.github.io/husky/#/?id=custom-directory
> 
> If we change the prepare script statement to `"prepare": "cd .. && husky install"`, it solves the issue but I am not sure that this is what we want. Can anyone confirm?

We would need to research what is the best way to use husky in a repository which contains multiple Node projects. Honestly that might be our solution @thejasonxie but let's look into it a bit further to make sure. I do find it weird that our husky would need to be installed on client but not the server when it would be running on both directories.

I wonder if we could also make a node project for the root folder for husky and prettier themselves. Nesting node projects though seems like a bad idea.

So let's all research it and compare solutions we could find. It shouldn't be too hard because it is  sometimes common for some projects to have client/server in the same repository.

**Comment by thejasonxie** [comment]
> > I get an error during npm install. When it gets to the prepare script, husky cannot find the .git directory. Husky is looking for the .git folder in the client directory when it is in the root project directory. reference: https://typicode.github.io/husky/#/?id=custom-directory
> > If we change the prepare script statement to `"prepare": "cd .. && husky install"`, it solves the issue but I am not sure that this is what we want. Can anyone confirm?
> 
> We would need to research what is the best way to use husky in a repository which contains multiple Node projects. Honestly that might be our solution @thejasonxie but let's look into it a bit further to make sure. I do find it weird that our husky would need to be installed on client but not the server when it would be running on both directories.
> 
> I wonder if we could also make a node project for the root folder for husky and prettier themselves. Nesting node projects though seems like a bad idea.
> 
> So let's all research it and compare solutions we could find. It shouldn't be too hard because it is sometimes common for some projects to have client/server in the same repository.

I wouldn't mind splitting the client and server into separate repository since it will be both under the team's organization. Otherwise, I'm not sure if there is another solution.

**Review by EHSANHAZARI — APPROVED** [review]

**Review by EHSANHAZARI — DISMISSED** [review]

**Review by thejasonxie — APPROVED** [review]
Setup husky and prettier, as well as fixed future merge conflicts with main

**Comment by thejasonxie** [comment]
> > I get an error during npm install. When it gets to the prepare script, husky cannot find the .git directory. Husky is looking for the .git folder in the client directory when it is in the root project directory. reference: https://typicode.github.io/husky/#/?id=custom-directory
> > If we change the prepare script statement to `"prepare": "cd .. && husky install"`, it solves the issue but I am not sure that this is what we want. Can anyone confirm?
> 
> We would need to research what is the best way to use husky in a repository which contains multiple Node projects. Honestly that might be our solution @thejasonxie but let's look into it a bit further to make sure. I do find it weird that our husky would need to be installed on client but not the server when it would be running on both directories.
> 
> I wonder if we could also make a node project for the root folder for husky and prettier themselves. Nesting node projects though seems like a bad idea.
> 
> So let's all research it and compare solutions we could find. It shouldn't be too hard because it is sometimes common for some projects to have client/server in the same repository.

It should be fine the way it is now. That is the only solution if you have two projects in a single repository. Server and Client directory have its own `.husky/pre-commit` hooks that both use the .git in the project root. `Server`'s pre-commit won't affect `client`'s pre-commit and vice versa. If we do plan on separating them to different repositories, we just need to remove the `cd` commands inside of both `server`'s and `client`'s `.husky/pre-commit` file

**Review by EHSANHAZARI — DISMISSED** [review]

**Review by oliviergoulet5 — APPROVED** [review]
Looks good to me! I would in the future change the prettier config file to get a better and less simplistic code styling.

**Review by thejasonxie — APPROVED** [review]

**Review by EHSANHAZARI — APPROVED** [review]

**Pull request merged**
